# Generated by Django 2.1.5 on 2020-08-21 05:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_body', models.TextField(help_text='Write your answer here...', max_length=2000)),
                ('created_date', models.DateField(default=datetime.datetime(2020, 8, 21, 5, 7, 7, 937568, tzinfo=utc), null=True)),
                ('updated_date', models.DateField(default=datetime.datetime(2020, 8, 21, 5, 7, 7, 937568, tzinfo=utc), null=True)),
                ('upvote', models.IntegerField(default=0)),
                ('downvote', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField(help_text='Enter your comment...', max_length=1000)),
                ('created_date', models.DateField(default=datetime.datetime(2020, 8, 21, 5, 7, 7, 953197, tzinfo=utc))),
                ('updated_date', models.DateField(default=datetime.datetime(2020, 8, 21, 5, 7, 7, 953197, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_body', models.TextField(help_text='Enter your question in brief', max_length=1000)),
                ('created_date', models.DateField(default=datetime.datetime(2020, 8, 21, 5, 7, 7, 937568, tzinfo=utc), null=True)),
                ('updated_date', models.DateField(default=datetime.datetime(2020, 8, 21, 5, 7, 7, 937568, tzinfo=utc), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(blank=True, max_length=70)),
                ('created_date', models.DateField(default=datetime.datetime(2020, 8, 21, 5, 7, 7, 937568, tzinfo=utc), null=True)),
                ('credit_points', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuoraApp.Writer'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuoraApp.Writer'),
        ),
        migrations.AddField(
            model_name='comment',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuoraApp.Answer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuoraApp.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuoraApp.Writer'),
        ),
    ]
