# Generated by Django 2.1.5 on 2020-08-21 05:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuoraApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 21, 5, 40, 51, 138735, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 21, 5, 40, 51, 138735, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 21, 5, 40, 51, 138735, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 21, 5, 40, 51, 138735, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 21, 5, 40, 51, 138735, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 21, 5, 40, 51, 138735, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 21, 5, 40, 51, 138735, tzinfo=utc), null=True),
        ),
    ]
