# Generated by Django 2.2.5 on 2020-08-21 09:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuoraApp', '0002_auto_20200821_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Writer',
            new_name='writer',
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 21, 9, 37, 37, 187125, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 21, 9, 37, 37, 187125, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 21, 9, 37, 37, 187125, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 21, 9, 37, 37, 187125, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 21, 9, 37, 37, 187125, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 21, 9, 37, 37, 187125, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 21, 9, 37, 37, 187125, tzinfo=utc), null=True),
        ),
    ]
